# Generated by Django 4.1.7 on 2023-04-07 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=12)),
                ("email", models.EmailField(max_length=254)),
                ("status", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MechanicsOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_content", models.CharField(max_length=1024)),
                ("offer_price", models.FloatField()),
                (
                    "client_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="offers.clientorder",
                    ),
                ),
            ],
        ),
    ]
