# Generated by Django 4.1.7 on 2023-05-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_mechanicoffer_delete_mechanicsoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='status',
            field=models.IntegerField(choices=[(0, 'Oczekiwanie na oferty mechanika'), (1, 'Oczekiwanie na decyzję klienta'), (2, 'Oczekiwanie na części'), (3, 'W trakcie naprawy'), (4, 'Gotowy do odbioru'), (5, 'Odebrany')], default=0),
        ),
    ]
