# Generated by Django 4.1.7 on 2023-05-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_clientorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=80)),
                ('item_description', models.TextField(default=None, null=True)),
                ('item_link', models.TextField(default=None, null=True)),
                ('item_price', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='mechanicoffer',
            old_name='offer_price',
            new_name='work_price',
        ),
        migrations.AddField(
            model_name='mechanicoffer',
            name='offer_items',
            field=models.ManyToManyField(to='offers.offeritem'),
        ),
    ]
